In [ ]:
import numpy as np
#Crea un tensor 3D a partir de listas.

lista1 = [100,200,300,400,500,600]
lista2 = [10,20,30,40,50,60]
lista3 = [1,2,3,4,5,6]

tensor= np.array([[lista1], [lista2], [lista3]])
print(tensor)

#Crea un array con 100 valores entre 6 y 9.
array = (np.linspace(6,9, 100))
print(array)

#Haz que el anterior array ahora tenga todos sus valores iguales a pi.
print(np.full_like(array, np.pi))

#Crea un array 1D de 10000 números aleatorios.
array1d = (np.random.randint(low= 0, high=10000, size= 10000))
print(array1d)


a = np.arange(1,10)
B = np.reshape(a, [3,3])
print(B)

#Intenta crear un array con diferentes tipos de datos (por ejemplo, enteros y flotantes). ¿Si usas .dtype(), qué tipo de dato es?
array = np.array([1.2, 1.85, 16, 'a'])
print(array)
print(array.dtype)

#Crea una matriz de 10 × 10 a partir de un vector secuencial (analiza cuál es la mejor solución, usar np.arange o np.linspace).




a = np.arange(1,10)
B = np.reshape(a, [3,3])
print(B)

a = np.arange(2,6,1)
b = np.reshape(a, [2,2])
display(a)
display(b)

c = np.arange(1,101,1)
d = np.reshape(c,[10,10])
display(c)
display(d)

e = np.linspace(1,101,100)
f = np.reshape(e, [10,10])
display(e)
display(f)       

#como podemos observar claramente la mejor forma es hacerlo con arrange


#Crea una matriz de 10 × 10 y accede a sus columnas 4, 5 y 6 y a sus filas 8 y 9.
vector = np.arange(1,101,1)
matriz = np.reshape(vector,[10,10])

display(matriz)
#Selecciona solo la fila 2
display(matriz[2, :])
#Crea un tensor de 2 × 10 × 10 e intenta replicar el ejercicio para la segunda matriz. ¿Qué tuviste que hacer diferente?
tensor = np.arange(200).reshape(2,10,10)
display(tensor)
print(tensor[1,1,:])
#le tuve que agregar un parametro mas



[[[100 200 300 400 500 600]]

 [[ 10  20  30  40  50  60]]

 [[  1   2   3   4   5   6]]]
[6.         6.03030303 6.06060606 6.09090909 6.12121212 6.15151515
 6.18181818 6.21212121 6.24242424 6.27272727 6.3030303  6.33333333
 6.36363636 6.39393939 6.42424242 6.45454545 6.48484848 6.51515152
 6.54545455 6.57575758 6.60606061 6.63636364 6.66666667 6.6969697
 6.72727273 6.75757576 6.78787879 6.81818182 6.84848485 6.87878788
 6.90909091 6.93939394 6.96969697 7.         7.03030303 7.06060606
 7.09090909 7.12121212 7.15151515 7.18181818 7.21212121 7.24242424
 7.27272727 7.3030303  7.33333333 7.36363636 7.39393939 7.42424242
 7.45454545 7.48484848 7.51515152 7.54545455 7.57575758 7.60606061
 7.63636364 7.66666667 7.6969697  7.72727273 7.75757576 7.78787879
 7.81818182 7.84848485 7.87878788 7.90909091 7.93939394 7.96969697
 8.         8.03030303 8.06060606 8.09090909 8.12121212 8.15151515
 8.18181818 8.21212121 8.24242424 8.27272727 8.3030303  8.33333333
 8.36363636 8.39393939 8.42424242 8.4545

array([2, 3, 4, 5])

array([[2, 3],
       [4, 5]])

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

array([  1.        ,   2.01010101,   3.02020202,   4.03030303,
         5.04040404,   6.05050505,   7.06060606,   8.07070707,
         9.08080808,  10.09090909,  11.1010101 ,  12.11111111,
        13.12121212,  14.13131313,  15.14141414,  16.15151515,
        17.16161616,  18.17171717,  19.18181818,  20.19191919,
        21.2020202 ,  22.21212121,  23.22222222,  24.23232323,
        25.24242424,  26.25252525,  27.26262626,  28.27272727,
        29.28282828,  30.29292929,  31.3030303 ,  32.31313131,
        33.32323232,  34.33333333,  35.34343434,  36.35353535,
        37.36363636,  38.37373737,  39.38383838,  40.39393939,
        41.4040404 ,  42.41414141,  43.42424242,  44.43434343,
        45.44444444,  46.45454545,  47.46464646,  48.47474747,
        49.48484848,  50.49494949,  51.50505051,  52.51515152,
        53.52525253,  54.53535354,  55.54545455,  56.55555556,
        57.56565657,  58.57575758,  59.58585859,  60.5959596 ,
        61.60606061,  62.61616162,  63.62626263,  64.63

array([[  1.        ,   2.01010101,   3.02020202,   4.03030303,
          5.04040404,   6.05050505,   7.06060606,   8.07070707,
          9.08080808,  10.09090909],
       [ 11.1010101 ,  12.11111111,  13.12121212,  14.13131313,
         15.14141414,  16.15151515,  17.16161616,  18.17171717,
         19.18181818,  20.19191919],
       [ 21.2020202 ,  22.21212121,  23.22222222,  24.23232323,
         25.24242424,  26.25252525,  27.26262626,  28.27272727,
         29.28282828,  30.29292929],
       [ 31.3030303 ,  32.31313131,  33.32323232,  34.33333333,
         35.34343434,  36.35353535,  37.36363636,  38.37373737,
         39.38383838,  40.39393939],
       [ 41.4040404 ,  42.41414141,  43.42424242,  44.43434343,
         45.44444444,  46.45454545,  47.46464646,  48.47474747,
         49.48484848,  50.49494949],
       [ 51.50505051,  52.51515152,  53.52525253,  54.53535354,
         55.54545455,  56.55555556,  57.56565657,  58.57575758,
         59.58585859,  60.5959596 ],
       [ 6

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

[110 111 112 113 114 115 116 117 118 119]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=3a030b5a-14f1-42be-a02d-9145dd4f2e0f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>